### ISSUE TITLE
[Bug] Chives dont open process Sleep

### ISSUE THREAD

**Issue by alsnet** [HiveProject2021/chives-blockchain#12]
### What happened?

[219834:0707/171859.233718:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
(node:219799) UnhandledPromiseRejectionWarning: YAMLException: duplicated mapping key (519:3)

 516 |   wallet_peers_file_path: wallet/ ...
 517 |   
 518 |   # Allow connecting to remote pe ...
 519 |   connect_to_unknown_peers: True
---------^
 520 | 
 521 |   logging: *logging
    at ro (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2257825)
    at so (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2257860)
    at uo (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2259892)
    at /usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2265052
    at wo (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2265329)
    at /usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2265006
    at wo (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2265329)
    at bo (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2272636)
    at vo (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2273379)
    at Object.load (/usr/lib/chives-blockchain/resources/app.asar/build/electron/main.js:2:2273604)
(Use `chives-blockchain --trace-warnings ...` to show where the warning was created)
(node:219799) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:219799) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Version

1.3.5

### What platform are you using?

Linux

### What ui mode are you using?

GUI

**Comment by Kelcyo** [comment]
I get the same error on several machines, both with Windows 11 and Windows 10...
What is the solution?
Does anyone have the installer of a previous version that is working perfectly?
