### ISSUE TITLE
[BUG] error sockets

### ISSUE THREAD

**Issue by jeromflo** [HiveProject2021/chives-blockchain#59]
This error ever happen

2021-12-01T23:43:55.633 full_node chives.full_node.full_node: WARNING  is_connected:True
2021-12-01T23:43:55.633 full_node chives.full_node.full_node: WARNING  synced:True
2021-12-01T23:43:55.930 harvester chives.rpc.rpc_server   : WARNING  Sending data failed. Exception Traceback (most recent call last):
  File "chives\rpc\rpc_server.py", line 67, in _state_changed
  File "aiohttp\client_ws.py", line 150, in send_str
  File "aiohttp\http_websocket.py", line 687, in send
  File "aiohttp\http_websocket.py", line 643, in _send_frame
  File "aiohttp\http_websocket.py", line 660, in _write
ConnectionResetError: Cannot write to closing transport

**Comment by onegoku** [comment]
Hey, in the newest version 1.2.11 this warning is gone.
